server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comicweb
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
comicweb:
  app:
    jwtSecret: comicwebSecretKey
    jwtExpirationMs: 86400000